setup-environment: Allow for downstream EULA updates
Freescale/fsl-community-bsp-base pull request #13
Opened 2020-03-28 18:01 UTC by thochstein

Add a variable so NXP can update the click-through EULA when they
release their layers.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>

2020-03-28 19:08 UTC, otavio requested changes

2020-03-28 19:08 UTC, otavio commented on setup-environment
> +fi
```
[ -z "$FSL_EULA_FILE" ] && FSL_EULA_FILE=$CWD/sources/meta-freescale/EULA
```

2020-04-04 16:20 UTC, thochstein commented
Ping

2020-04-06 19:07 UTC, otavio commented
Please extend the commit log explaining the reasoning and use case for this. I think I get the use case for it but it must be documented.

2020-04-09 12:54 UTC, thochstein commented
> Please extend the commit log explaining the reasoning and use case for this. I think I get the use case for it but it must be documented.

Done.

2020-04-09 13:02 UTC, otavio approved these changes

2020-04-09 13:03 UTC, merged